version: '3.8'

services:
  app:
    image: phone-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    container_name: phone-frontend-dev
  server:
    image: phone-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001
    environment: 
      - MONGODB_URI=mongodb+srv://teemuo-fullstack:<password>@cluster0.pufz2.mongodb.net/phonebook?retryWrites=true
      - PORT=3001
    container_name: phone-backend-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-dev